---
title: "Covid Dashboard"
author: "Nicolas Vecchione"
date: "Last Updated: `r format(Sys.time(), '%d/%m/%Y %H:%M:%S')`"
output: 
  html_document:
    css: mystyles.css
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source_functions, echo=FALSE,message=FALSE, warning=FALSE}
#extracting the latest data (updating git + calculated data)
source("JHGetData.R", encoding='utf-8')
#JH plotting and data extracting functions
source("JHFunctions.R")

library(tidyverse)
library(lubridate)
options(digits = 3)   # report 3 significant digits
options(scipen = -2)
```

## Country Rankings

```{r rankings,echo=FALSE,message=FALSE, warning=FALSE}
#adding abbreviation table
library(knitr)
library(kableExtra)

last_day <- master_data %>% pull(Date) %>% max()
ntop <- 20
top_Deaths <- master_data %>%
  filter(Date == last_day) %>%
  slice_max(order_by = Deaths,n=ntop) %>% 
  select(Country_Region,Deaths)

top_Weighted_Deaths <- master_data %>%
  filter(Date == last_day) %>%
  slice_max(order_by = Weighted_Deaths,n=ntop) %>% 
  select(Country_Region,Weighted_Deaths)

top_Weighted_Confirmed <- master_data %>%
  filter(Date == last_day) %>%
  slice_max(order_by = Weighted_Deaths,n=ntop) %>% 
  select(Country_Region,Weighted_Confirmed)


top_Increase_Weighted_Deaths <- master_data %>%
  filter(Date == last_day) %>%
  slice_max(order_by = Increase_Weighted_Deaths,n=ntop) %>%
  select(Country_Region,Increase_Weighted_Deaths)
top_Increase_Weighted_Confirmed <- master_data %>%
  filter(Date == last_day) %>%
  slice_max(order_by = Increase_Weighted_Confirmed,n=ntop) %>%
  select(Country_Region,Increase_Weighted_Confirmed)
```

### Totals

```{r totals_tables,echo=FALSE,message=FALSE, warning=FALSE}
options(digits = 3)   # report 3 significant digits
#options(scipen = -2)
#adding abbreviation table
library(knitr)
library(kableExtra)

kable(x=top_Deaths,caption=paste("Top",ntop,"Countries - Total Deaths")) %>%
  kable_styling(full_width = F) 

kable(x=top_Weighted_Deaths,caption=paste("Top",ntop,"Countries - Total Weighted Deaths","per",scaling_death,"people")) %>%
  kable_styling(full_width = F) 

kable(x=top_Weighted_Confirmed,caption=paste("Top",ntop,"Countries - Total Weighted Confirmed","per",scaling_confirmed,"people"),format = "html") %>%
  kable_styling(full_width = F) 

```

### Increases

```{r increases_tables,echo=FALSE,message=FALSE, warning=FALSE}
options(digits = 3)   # report 3 significant digits
options(scipen = -2)
#adding abbreviation table
library(knitr)
library(kableExtra)

kable(x=top_Increase_Weighted_Deaths,caption=paste("Top",ntop,"Countries - Increase Weighted Deaths","per",scaling_death,"people")) %>%
  kable_styling(full_width = F) 

kable(x=top_Increase_Weighted_Confirmed,caption=paste("Top",ntop,"Countries - Increase Weighted Confirmed","per",scaling_confirmed,"people")) %>%
  kable_styling(full_width = F) 

```

## Plots

### Increases

```{r  warning=FALSE}
CountryList <- c("United Kingdom","France","Italy","Germany","Belgium","Spain","Greece","Sweden","Norway","Finland","United States")
```


```{r  warning=FALSE}
p <- master_data %>%
  JHplot_CountryLevel(CountryList,"Deaths")
p
```

```{r  warning=FALSE}
p <- master_data %>%
  JHplot_CountryLevel(CountryList,"Weighted_Deaths")
p
```


```{r plots1, warning=FALSE}
p <- master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Deaths_Avg_Avg")
p
```

```{r plots2, warning=FALSE}
p <- master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Weighted_Deaths_Avg_Avg")
p
```


```{r plots3, warning=FALSE}
p <- master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Confirmed_Avg_Avg")
p
```


```{r plots4, warning=FALSE}
p <- master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Weighted_Confirmed_Avg_Avg")
p
```
