---
title: "Covid Data Observation"
author: "Nicolas Vecchione"
date: "Last Updated: `r format(Sys.time(), '%d/%m/%Y %H:%M:%S')`"
output: 
  html_document:
    css: mystyles.css
    toc: true
    toc_depth: 3
    toc_float: true
  pdf_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = '..')
knitr::opts_chunk$set(echo = TRUE)
# chunk option dev="svg" produces very large vector graphics files
knitr::opts_chunk$set(dev="svg")
# chunk option dev="png" is the default raster graphics format for HTML output
knitr::opts_chunk$set(dev="png")
# set default dpi and width 
knitr::opts_chunk$set(dpi=300,
                      out.width="800px", 
                      out.height = "600px")

if(knitr::is_html_output()) {
  simple_plot_type <- FALSE
} else {
  simple_plot_type <- TRUE
}
#Setting up larger memory allowance, for more demanding models and systems with limited memory 
gc()
memory.limit(size=100000)
```

```{r source_functions, echo=FALSE,message=FALSE, warning=FALSE}
#extracting the latest data (updating git + calculated data)
getwd()
#JH plotting and data extracting functions
source("./Functions/JHFunctions.R")
source("./Scripts/JHGetData.R", encoding='utf-8')


library(tidyverse)
library(lubridate)
options(digits = 3)   # report 3 significant digits
options(scipen = -2)
```


## Country Rankings

```{r rankings,echo=FALSE,message=FALSE, warning=FALSE}
#adding abbreviation table
library(knitr)
library(kableExtra)

last_day <- master_data %>% pull(Date) %>% max()
ntop <- 20

#totals
top_Deaths <- master_data %>%
  Top_N_CountryLevel(VarName = "Deaths",
                                  datetop = last_day,
                                  ntop = ntop)

top_Weighted_Deaths <- master_data %>%
  Top_N_CountryLevel(VarName = "Weighted_Deaths",
                                  datetop = last_day,
                                  ntop = ntop)

#increase
top_Increase_Deaths_Avg_Avg <- master_data %>%
  Top_N_CountryLevel(VarName = "Increase_Deaths_Avg_Avg",
                                  datetop = last_day,
                                  ntop = ntop)

top_Increase_Confirmed_Avg_Avg <- master_data %>%
  Top_N_CountryLevel(VarName = "Increase_Confirmed_Avg_Avg",
                                  datetop = last_day,
                                  ntop = ntop)

top_Increase_Weighted_Deaths_Avg_Avg <- master_data %>%
  Top_N_CountryLevel(VarName = "Increase_Weighted_Deaths_Avg_Avg",
                                  datetop = last_day,
                                  ntop = ntop)

top_Increase_Weighted_Confirmed_Avg_Avg <- master_data %>%
  Top_N_CountryLevel(VarName = "Increase_Weighted_Confirmed_Avg_Avg",
                                  datetop = last_day,
                                  ntop = ntop)
```
### Increases

```{r increases_deaths_tables,echo=FALSE,message=FALSE, warning=FALSE}
options(digits = 3)   # report 3 significant digits
options(scipen = -2)
#adding abbreviation table
library(knitr)
library(kableExtra)

#TODO: function to keep order for pdf version

kable(x=top_Increase_Deaths_Avg_Avg,caption=paste("Top",ntop,"Countries - Increase Deaths Avg Avg")) %>%
  kable_styling(full_width = F) 

kable(x=top_Increase_Weighted_Deaths_Avg_Avg,caption=paste("Top",ntop,"Countries - Increase Weighted Deaths Avg","per",scaling_death,"people")) %>%
  kable_styling(full_width = F)
```


```{r increases_confirmed_tables,echo=FALSE,message=FALSE, warning=FALSE}
kable(x=top_Increase_Confirmed_Avg_Avg,caption=paste("Top",ntop,"Countries - Increase Confirmed Avg Avg")) %>%
  kable_styling(full_width = F) 

kable(x=top_Increase_Weighted_Confirmed_Avg_Avg,caption=paste("Top",ntop,"Countries - Increase Weighted Confirmed Avg","per",scaling_confirmed,"people")) %>%
  kable_styling(full_width = F) 

```

### Totals

```{r totals_deaths_tables,echo=FALSE,message=FALSE, warning=FALSE}
options(digits = 3)   # report 3 significant digits
#options(scipen = -2)
#adding abbreviation table
library(knitr)
library(kableExtra)

kable(x=top_Deaths,caption=paste("Top",ntop,"Countries - Total Deaths")) %>%
  kable_styling(full_width = F) 

kable(x=top_Weighted_Deaths,caption=paste("Top",ntop,"Countries - Total Weighted Deaths","per",scaling_death,"people")) %>%
  kable_styling(full_width = F) 

```

## Maps

```{r mapattempt,echo=FALSE,message=FALSE, warning=FALSE, eval = FALSE}
# lat_long <- master_data %>% 
#   filter(is.na(Province_State)) %>%
#   select(Country_Region,Lat,Long) %>% 
#   unique() #this does not pick anything for countries who only have region longitudes and latitudes
# 
# contrieswithmissinglonglat <- master_data %>% select(Country_Region) %>% unique() %>% anti_join(lat_long)
# # 
# #   Country_Region
# #   <chr>         
# # 1 Australia     
# # 2 Canada        
# # 3 China  
# 
# calc_lat_long <- master_data %>% 
#   select(Country_Region,Province_State,Lat,Long) %>% 
#   filter(Country_Region %in% contrieswithmissinglonglat$Country_Region) %>%
#   filter(!is.na(Lat),!is.na(Long),!(Lat == 0 & Long == 0)) %>%
#   unique() %>%
#   group_by(Country_Region) %>%
#   summarise(Lat = mean(Lat), Long = mean(Long))
# 
# lat_long <- lat_long %>%
#   bind_rows(calc_lat_long)
# 
# Covid19mapdata <- top_Weighted_Deaths %>%
#   full_join(top_Deaths) %>%
#   full_join(top_Weighted_Deaths) %>%
#   full_join(top_Increase_Deaths_Avg_Avg) %>%
#   full_join(top_Increase_Weighted_Deaths_Avg_Avg) %>%
#   full_join(top_Increase_Confirmed_Avg_Avg) %>%
#   full_join(top_Increase_Weighted_Confirmed_Avg_Avg) %>%
#   left_join(lat_long) 
# 
# Covid19mapdata <- Covid19mapdata %>%
#   rename(Inc_Weighted_Deaths = Increase_Weighted_Deaths_Avg_Avg ) %>%
#   rename(Inc_Weighted_Confirmed = Increase_Weighted_Confirmed_Avg_Avg )%>%
#   rename(Inc_Deaths = Increase_Deaths_Avg_Avg )%>%
#   rename(Inc_Confirmed = Increase_Confirmed_Avg_Avg )
# 
# Covid19 <- sf::st_as_sf(Covid19mapdata, coords = c("Long","Lat"))
# 
# sf::st_crs(Covid19 ) <- 4326
# Covid19$Easting <- Covid19$Northing <- NULL
# 
# inc_deaths_data <-  Covid19mapdata   %>% 
#   mutate(cex_val_inc_deaths = Inc_Deaths - min(Inc_Deaths,na.rm = TRUE)#Inc_Weighted_Deaths- min(Inc_Weighted_Deaths)
#          ) 
# 
# #inc_deaths_data_sf <-  
# 
# cex_val_inc_weighted_deaths  <- Covid19mapdata   %>% 
#   mutate(cex_val_inc_weighted_deaths = Inc_Weighted_Deaths - min(Inc_Weighted_Deaths,na.rm = TRUE)#Inc_Weighted_Deaths- min(Inc_Weighted_Deaths)
#          ) %>%
#   select(Country_Region,cex_val_inc_weighted_deaths) 
# 
# map_inc_deaths <- mapview::mapview(Covid19,
#                  zcol = "Inc_Deaths",
#                  label = paste(Covid19$Country_Region,
#                                "\n",
#                                as.integer(Covid19$Inc_Deaths)),
#                  cex=cex_val_inc_deaths$cex_val_inc_deaths,
#                  col.regions = hcl.colors(10, 
#                                           palette = "viridis",#"zissou 1"
#                                           ),
#                  legend = TRUE
#                  )
# 
# map_inc_weighted_deaths <- mapview::mapview(Covid19,
#                  zcol = "Inc_Weighted_Deaths",
#                  label = paste(Covid19$Country_Region,
#                                "\n",
#                                as.integer(Covid19$Inc_Weighted_Deaths)),
#                  cex=cex_val_inc_weighted_deaths$cex_val_inc_weighted_deaths,
#                  col.regions = hcl.colors(10, 
#                                           palette = "viridis",#"zissou 1"
#                                           ),
#                  legend = TRUE
#                  )
# 
# map_inc_deaths + map_inc_weighted_deaths
# map_inc_deaths
# map_inc_weighted_deaths 


```


## Plots


```{r  warning=FALSE}
# CountryList <- bind_rows(top_Increase_Weighted_Deaths_Avg_Avg %>% select(Country_Region),
#                  top_Increase_Deaths_Avg_Avg%>% select(Country_Region),
#                  top_Deaths %>% select(Country_Region)) %>% unique() %>% pull(Country_Region)
# CountryList <- unique(c(top_Increase_Weighted_Deaths_Avg_Avg$Country_Region,
#                  top_Increase_Deaths_Avg_Avg$Country_Region,
#                  top_Deaths$Country_Region,
#                  
#                  "Portugal"))
CountryList <- c("United Kingdom","France","Italy","Germany",#"Belgium",
                 "Spain"#,"Greece"#,
                 #"Sweden","Norway","Finland","Czech Republic","Peru", "United States", "Brazil"
                 )
```


### Increases

```{r echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Deaths_Avg_Avg",simple = simple_plot_type)

```

```{r  echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Weighted_Deaths_Avg_Avg",simple = simple_plot_type,mindiffval = 0.1)
```


```{r  echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Confirmed_Avg_Avg",simple = simple_plot_type)
```

```{r  echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"Increase_Weighted_Confirmed_Avg_Avg",simple = simple_plot_type)
```

### Totals

```{r echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"Deaths",simple = simple_plot_type)
```

```{r  echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"Weighted_Deaths",simple = simple_plot_type)
```

```{r echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"People_partially_vaccinated",simple = simple_plot_type)
```

```{r echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"People_partially_vaccinated_Perc",simple = simple_plot_type)
```


```{r echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"People_fully_vaccinated",simple = simple_plot_type)
```

```{r echo=FALSE,message=FALSE, warning=FALSE}
master_data %>%
  JHplot_CountryLevel(CountryList,"People_fully_vaccinated_Perc",simple = simple_plot_type)
```